In [ ]:
import numpy as np
import random
from timeit import timeit
def add_python(z1,z2):
  for z1,z2 in zip(z1,z2):
    return z1+z2;
def add_numpy(z1,z2):
  return np.add(z1,z2);
size= 100000;
z1 = random.sample(range(size + 1),100)
z2 = random.sample(range(size + 1),100)
python_time = timeit("add_python(z1,z2)",globals=globals(),number=10000)
numpy_time = timeit("add_numpy(z1,z2)",globals=globals(),number=10000)
print("python time",python_time)
print("numpy time",numpy_time)

python time 0.005663642000001801
numpy time 0.1404667059999838


In [ ]:
import numpy as np
zeros_arry = np.zeros((2,3))
print("zero arra :\n", zeros_arry, "\nwith dimensions", zeros_arry.shape)

zero arra :
 [[0. 0. 0.]
 [0. 0. 0.]] 
with dimensions (2, 3)


In [ ]:
import numpy as np
zero_dim_array = np.array(5)
one_dim_array = np.array([1,2,3,4,5])
two_dim_array = np.array([[1,2,3],[4,5,6]])
for arr in [zero_dim_array,one_dim_array,two_dim_array]:
  print(arr,arr.ndim)

5 0
[1 2 3 4 5] 1
[[1 2 3]
 [4 5 6]] 2


In [ ]:
array_0d = np.array(5)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
for i, arry in enumerate([array_0d,array_1d,array_2d,array_3d]):
  print("array",arry,"shape",arry.shape)


array 5 shape ()
array [1 2 3 4 5] shape (5,)
array [[1 2 3]
 [4 5 6]] shape (2, 3)
array [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] shape (2, 2, 3)


In [ ]:
array= np.array([[1,2,3],[4,5,6]])
reshaped_array = array.reshape(3,2)
print("original array:", array)
print("reshaped array:", reshaped_array)

original array: [[1 2 3]
 [4 5 6]]
reshaped array: [[1 2]
 [3 4]
 [5 6]]


In [ ]:

a = np.arange(1 , 10)
print( a )
x = range(1 , 10)
print( x ) # x is an iterator
print( list ( x ) )
# further arange examples :
x = np.arange (10.4)
print( x )
x = np.arange (0.5 , 10.4 , 0.8)
print( x )

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [20]:
print(np.linspace(1,10))
print(np.linspace(1,10,7))
print(np.linspace(1,10,7,endpoint = False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]
