In [2]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [5]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [4]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [6]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [7]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [9]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0.00000000e+000 1.21918118e-311]
 [1.21918118e-311 1.21918118e-311]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.00000000e+000 1.21919711e-311 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [14]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


In [16]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3 -3 -3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5 ]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [17]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


In [18]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
print("2-Norm (Euclidean):", np.linalg.norm(A))
print("Solution x:", np.linalg.solve(A, B))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


In [22]:
#1. Initialize an empty array with size 2X2.
import numpy as np
array2x2 = np.zeros((2,2))
print(array2x2)

[[0. 0.]
 [0. 0.]]


In [23]:
#2. Initialize an all one array with size 4X2.
import numpy as np
array4x2 = np.ones((4,2))
print(array4x2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
array_filled = np.full((3, 6), 7, dtype=int)
print(array_filled)


[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [27]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np
array_zeros = np.zeros_like(array_filled)
print(array_zeros)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [28]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
array_ones = np.ones_like(array_zeros)
print(array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [29]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("new list: ",new_list)
print("numpy array: ",numpy_array)

new list:  [1, 2, 3, 4]
numpy array:  [1 2 3 4]


In [30]:
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array_with_values = np.arange(10,50)#gives a range from 10 to under 50 (49)
print(array_with_values)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [31]:
#2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
array = np.arange(9)#single argument means the function puts value from 0 to whatever the argument is
matrix3x3 = np.reshape(array,(3,3))#name of array, shape of matrix
print(matrix3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)
meanOfArray = np.mean(random_array)
print("random array = ",random_array)
print("mean of the array = ",meanOfArray)

random array =  [0.10913591 0.42663095 0.15288593 0.81014269 0.50557516 0.30639201
 0.99581065 0.65648005 0.7708585  0.82916943 0.10585548 0.97900688
 0.5670584  0.42552702 0.84001626 0.95362373 0.01301467 0.11172744
 0.14346077 0.72213014 0.50480636 0.89216953 0.56129105 0.79848413
 0.42166336 0.31613434 0.92446692 0.11049679 0.41723683 0.22020853]
mean of the array =  0.519715330539528


In [44]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np

# Create a 10x10 array with random values
array10x10 = np.random.random(100)

# Reshape the array into a 10x10 matrix
matrix10x10 = np.reshape(array10x10, (10, 10))

# Find the minimum and maximum values
min_value = matrix10x10.min()
max_value = matrix10x10.max()

# Print the array, matrix, minimum value, and maximum value
print("Random 10x10 array:", array10x10)
print("\n10x10 matrix:\n", matrix10x10)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 array: [0.925765   0.36457456 0.34980399 0.80669684 0.95015189 0.79572269
 0.58147418 0.5304224  0.92690726 0.46556101 0.11784666 0.18586517
 0.12564701 0.35390353 0.46344172 0.849877   0.51804496 0.0252568
 0.39384847 0.53861349 0.97298342 0.80192195 0.81550337 0.28761005
 0.64022017 0.53903798 0.55831267 0.02947842 0.07198186 0.04902331
 0.77381251 0.4461732  0.23372876 0.37768658 0.47315659 0.21151411
 0.69326068 0.04190348 0.73600471 0.90030482 0.69638718 0.32721586
 0.88769946 0.11704152 0.15009084 0.92755579 0.5916897  0.15058237
 0.69810637 0.72241633 0.21727884 0.16379078 0.9954794  0.3286131
 0.35176819 0.45432821 0.65709932 0.22286418 0.16711403 0.68202658
 0.01662247 0.5629465  0.04267405 0.90151916 0.76758836 0.04550291
 0.8856149  0.56036359 0.60906428 0.52096398 0.99613593 0.45957146
 0.54970059 0.65570535 0.76656172 0.66373239 0.35498621 0.590813
 0.47490151 0.30631275 0.84114957 0.09037449 0.05667779 0.13149981
 0.20472625 0.893107   0.90193849 0.61725251 0

In [47]:
#6. Create a zero array of size 10 and replace 5th element with 1.
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [49]:
#7. Reverse an array arr = [1,2,0,0,4,0].
arr = [1,2,0,0,4,0]
reversed_arr = np.flip(arr)#flips arr
print(reversed_arr)

[0 4 0 0 2 1]


In [50]:
#8. Create a 2d array with 1 on border and 0 inside.
import numpy as np

# Define the size of the 2D array
rows, cols = 5, 5

# Create an array filled with ones
array = np.ones((rows, cols), dtype=int)

# Fill the inside with zeros
array[1:-1, 1:-1] = 0

# Print the array
print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [51]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

# Create an 8x8 matrix
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

# Print the checkerboard pattern
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
#For the following arrays:
x = np.array([[1,2],[3,5]]) 
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
#1. Add the two array.
x_y_concat = np.concatenate((x,y),axis = 0)
v_w_concat = np.concatenate((v,w))
print(x_y_concat)
print(v_w_concat)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [60]:
#2. Subtract the two array.
# Subtract the arrays
x_y_subtract = x - y
v_w_subtract = v - w
# Print the results
print("x - y:\n", x_y_subtract)
print("v - w:", v_w_subtract)

x - y:
 [[-4 -4]
 [-4 -3]]
v - w: [-2 -2]


In [62]:
#3. Multiply the array with any integers of your choice.

x_multiplied = x * 3
y_multiplied = y * 3
v_multiplied = v * 3
w_multiplied = w * 3

# Print the results
print("x multiplied by", 3, ":\n", x_multiplied)
print("y multiplied by", 3, ":\n", y_multiplied)
print("v multiplied by", 3, ":", v_multiplied)
print("w multiplied by", 3, ":", w_multiplied)


x multiplied by 3 :
 [[ 3  6]
 [ 9 15]]
y multiplied by 3 :
 [[15 18]
 [21 24]]
v multiplied by 3 : [27 30]
w multiplied by 3 : [33 36]


In [63]:
#4. Find the square of each element of the array.
# Find the square of each element using `np.square`
x_squared_np = np.square(x)
y_squared_np = np.square(y)
v_squared_np = np.square(v)
w_squared_np = np.square(w)

# Print the results using `np.square`
print("\nUsing np.square:")
print("Square of each element in x:\n", x_squared_np)
print("Square of each element in y:\n", y_squared_np)
print("Square of each element in v:", v_squared_np)
print("Square of each element in w:", w_squared_np)


Using np.square:
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Square of each element in y:
 [[25 36]
 [49 64]]
Square of each element in v: [ 81 100]
Square of each element in w: [121 144]


In [64]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

# Calculate the dot products
dot_product_v_w = np.dot(v, w)
dot_product_x_v = np.dot(x, v)
dot_product_x_y = np.dot(x, y)

# Print the results
print("Dot product between v and w:", dot_product_v_w)
print("Dot product between x and v:\n", dot_product_x_v)
print("Dot product between x and y:\n", dot_product_x_y)


Dot product between v and w: 219
Dot product between x and v:
 [29 77]
Dot product between x and y:
 [[19 22]
 [50 58]]


In [65]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.
# Concatenate along rows (axis=0)
xy_concat_rows = np.concatenate((x, y), axis=0)

# Print the result
print("Concatenate x and y along rows:\n", xy_concat_rows)

# Stack them as columns
vw_concat_columns = np.vstack((v, w)).T

# Print the result
print("Concatenate v and w along columns:\n", vw_concat_columns)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [66]:
# Concatenate x and v
try:
    xv_concat = np.concatenate((x, v))
    print("Concatenate x and v:\n", xv_concat)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [74]:
#For the following arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);
#Prove following with Numpy:
#1. Prove A.A−1 = I.
I = np.eye(2)
A_ = np.linalg.inv(A)
Result = np.dot(A,A_)
print("I = \n",I)
print("A.A-1 = \n",Result,"\n")
    
#2. Prove AB ̸= BA.
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB = \n",AB)
print("BA = \n",BA,"\n")
#3. Prove (AB)T = BTAT
# Calculate (AB)^T
AB_T = np.transpose(AB)

# Calculate B^T
B_T = np.transpose(B)

# Calculate A^T
A_T = np.transpose(A)

# Calculate B^T A^T
BT_AT = np.dot(B_T, A_T)

# Print the results
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)


I = 
 [[1. 0.]
 [0. 1.]]
A.A-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]] 

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]] 

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]


In [77]:
#Solve the following system of Linear equation using Inverse Methods.

#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9

# Define the matrices A and B
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply the inverse of A with B to find X
X = np.dot(A_inv, B)

# Print the result
print("(x, y, z) = ", X)


(x, y, z) =  [ 2.  1. -2.]


In [78]:
#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

# Define the coefficient matrix A and the constant matrix B
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Calculate the inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# Solve for X using the inverse of A
X = np.dot(A_inv, B)

# Print the result
print("(x, y, z) = ", X)


(x, y, z) =  [ 2.  1. -2.]


In [80]:
#• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure the time taken for element-wise addition
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()

# Print the time taken
print("Time taken using Python lists:", end_time - start_time, "seconds")


Time taken using Python lists: 0.18282198905944824 seconds


In [81]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure the time taken for element-wise addition
start_time = time.time()
array_sum = array1 + array2
end_time = time.time()

# Print the time taken
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Time taken using NumPy arrays: 0.0040204524993896484 seconds


In [82]:
#• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure the time taken for element-wise multiplication
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()

# Print the time taken
print("Time taken using Python lists:", end_time - start_time, "seconds")


Time taken using Python lists: 0.19166278839111328 seconds


In [83]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure the time taken for element-wise multiplication
start_time = time.time()
array_product = array1 * array2
end_time = time.time()

# Print the time taken
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Time taken using NumPy arrays: 0.0034220218658447266 seconds


In [84]:
#Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure the time taken to compute the dot product
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()

# Print the time taken and the result
print("Dot product using Python lists:", dot_product)
print("Time taken using Python lists:", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.19921636581420898 seconds


In [85]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure the time taken to compute the dot product
start_time = time.time()
dot_product_np = np.dot(array1, array2)
end_time = time.time()

# Print the time taken and the result
print("Dot product using NumPy arrays:", dot_product_np)
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Dot product using NumPy arrays: 333332833333500000
Time taken using NumPy arrays: 0.0019469261169433594 seconds


In [3]:
#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
import time

# Create two 1000x1000 matrices using Python lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

# Measure the time taken for matrix multiplication
start_time = time.time()

result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

end_time = time.time()

# Print the time taken
print("Time taken using Python lists: {:.4f} seconds".format(end_time - start_time))


Time taken using Python lists: 185.5761 seconds


In [1]:
#• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
import numpy as np
import time

# Create two 1000x1000 matrices using NumPy arrays
matrix1 = np.random.randint(0, 100, size=(1000, 1000))
matrix2 = np.random.randint(0, 100, size=(1000, 1000))

# Measure the time taken for matrix multiplication
start_time = time.time()

result = np.dot(matrix1, matrix2)

end_time = time.time()

# Print the time taken
print("Time taken using NumPy arrays: {:.4f} seconds".format(end_time - start_time))


Time taken using NumPy arrays: 1.5370 seconds
